const HOST_URL = process.env.REACT_APP_HOST_URL;
const HOST_API = process.env.REACT_APP_HOST_API;
const HOST_DIGITAL_IDENTITY_API = process.env.REACT_APP_HOST_DIGITAL_IDENTITY_API;
const HOST_API_USER = process.env.REACT_APP_HOST_API_USER;
const HOST_API_SERVICE = process.env.REACT_APP_HOST_API_SERVICE;
const HOST_API_RENIEC = process.env.REACT_APP_HOST_API_RENIEC;
const ACCESS_KEY_ID = `${process.env.REACT_APP_ACCESS_KEY_ID}`;

const AWS_COGNITO_USER_POOL_ID = `${process.env.REACT_APP_USER_POOL_ID}`;
const AWS_IDENTITY_POOL_ID = `${process.env.REACT_APP_IDENTITY_POOL_ID}`;
const AWS_COGNITO_APP_CLIENT_ID = `${process.env.REACT_APP_CLIENT_ID}`;
const SECRET_ACCESS_KEY = `${process.env.REACT_APP_SECRET_ACCESS_KEY}`;
const AWS_REGION = `${process.env.REACT_APP_REGION}`;

const AWS_COGNITO_IDENTITY_POOL_ID = `${process.env.REACT_APP_IDENTITY_POOL_ID}`;

const JWT_PREFIX = `${process.env.REACT_APP_JWT_PREFIX}`;

//Sellers
const COMMUNITY_BASE_URL_S3 = `${process.env.REACT_APP_COMMUNITY_BASE_URL_S3}`;

//Otros
const TIME_ZONE = `${process.env.TIME_ZONE}`;

export {
  HOST_URL,
  HOST_API_RENIEC,
  HOST_API_USER,
  HOST_API_SERVICE,
  AWS_COGNITO_USER_POOL_ID,
  AWS_IDENTITY_POOL_ID,
  AWS_COGNITO_APP_CLIENT_ID,
  ACCESS_KEY_ID,
  SECRET_ACCESS_KEY,
  AWS_REGION,
  HOST_API,
  HOST_DIGITAL_IDENTITY_API,
  AWS_COGNITO_IDENTITY_POOL_ID,
  COMMUNITY_BASE_URL_S3,
  JWT_PREFIX,
  TIME_ZONE
};
